export const REGIONS = [
  'Afghanistan',
  'Albania', 
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo, Democratic Republic of the',
  'Congo, Republic of the',
  'Costa Rica',
  'Ivoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'São Tomé and Príncipe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

export const INDUSTRIES = [
  'Accounting',
  'Apparel & Fashion',
  'Architecture & Planning',
  'Automotive',
  'Building Materials',
  'Business Supplies & Equipment',
  'Chemicals',
  'Civic & Social Organization',
  'Civil Engineering',
  'Computer Software',
  'Construction',
  'Consumer Goods',
  'Consumer Services',
  'Design',
  'E-Learning',
  'Education Management',
  'Electrical/Electronic Manufacturing',
  'Entertainment',
  'Environmental Services',
  'Events Services',
  'Facilities Services',
  'Farming',
  'Financial Services',
  'Food & Beverages',
  'Food Production',
  'Furniture',
  'Government Administration',
  'Health, Wellness & Fitness',
  'Higher Education',
  'Hospitality',
  'Hospital & Health Care',
  'Human Resources',
  'Individual & Family Services',
  'Information Technology & Services',
  'Insurance',
  'Internet',
  'Investment Management',
  'Law Practice',
  'Legal Services',
  'Leisure, Travel & Tourism',
  'Machinery',
  'Management Consulting',
  'Marketing & Advertising',
  'Mechanical or Industrial Engineering',
  'Media Production',
  'Medical Device',
  'Medical Practice',
  'Mining & Metals',
  'Motion Pictures & Film',
  'Music',
  'Non-Profit Organization Management',
  'Oil & Energy',
  'Package/Freight Delivery',
  'Paper & Forest Products',
  'Performing Arts',
  'Photography',
  'Plastics',
  'Primary/Secondary Education',
  'Professional Training & Coaching',
  'Publishing',
  'Real Estate',
  'Recreational Facilities & Services',
  'Religious Institutions',
  'Research',
  'Restaurants',
  'Retail',
  'Sports',
  'Staffing & Recruiting',
  'Supermarkets',
  'Telecommunications',
  'Textiles',
  'Transportation/Trucking/Railroad',
  'Utilities',
  'Veterinary',
  'Wholesale'
];

export const DEPARTMENTS = [
  'Accounting & Finance',
  'Administration',
  'Analytics & Data Science',
  'Audit & Compliance',
  'Brand Management',
  'Business Development',
  'Communications',
  'Corporate Strategy',
  'Customer Service',
  'Design',
  'Digital Marketing',
  'Engineering',
  'Events & Public Relations',
  'Facilities Management',
  'Health & Safety',
  'Human Resources',
  'Information Technology',
  'Innovation & Research',
  'International Operations',
  'Legal',
  'Logistics & Supply Chain',
  'Marketing',
  'Operations',
  'Product Development',
  'Production & Manufacturing',
  'Project Management',
  'Quality Assurance',
  'Research & Development',
  'Risk Management',
  'Sales & Business Development',
  'Security',
  'Supply Chain Management',
  'Technical Support',
  'Training & Development',
  'Treasury & Investment'
];

export const COMPANY_SIZES = [
  'Micro (1-50)',
  'Small (51-500)',
  'Medium (501-1000)',
  'Large (1000-5000)',
  'Enterprise (5000+)'
];