export const REGIONS = [
  'North America',
  'Europe',
  'Asia',
  'South America',
  'Africa',
  'Oceania'
];

export const INDUSTRIES = [
  'Accounting',
  'Apparel & Fashion',
  'Architecture & Planning',
  'Automotive',
  'Building Materials',
  'Business Supplies & Equipment',
  'Chemicals',
  'Civic & Social Organization',
  'Civil Engineering',
  'Computer Software',
  'Construction',
  'Consumer Goods',
  'Consumer Services',
  'Design',
  'E-Learning',
  'Education Management',
  'Electrical/Electronic Manufacturing',
  'Entertainment',
  'Environmental Services',
  'Events Services',
  'Facilities Services',
  'Farming',
  'Financial Services',
  'Food & Beverages',
  'Food Production',
  'Furniture',
  'Government Administration',
  'Health, Wellness & Fitness',
  'Higher Education',
  'Hospitality',
  'Hospital & Health Care',
  'Human Resources',
  'Individual & Family Services',
  'Information Technology & Services',
  'Insurance',
  'Internet',
  'Investment Management',
  'Law Practice',
  'Legal Services',
  'Leisure, Travel & Tourism',
  'Machinery',
  'Management Consulting',
  'Marketing & Advertising',
  'Mechanical or Industrial Engineering',
  'Media Production',
  'Medical Device',
  'Medical Practice',
  'Mining & Metals',
  'Motion Pictures & Film',
  'Music',
  'Non-Profit Organization Management',
  'Oil & Energy',
  'Package/Freight Delivery',
  'Paper & Forest Products',
  'Performing Arts',
  'Photography',
  'Plastics',
  'Primary/Secondary Education',
  'Professional Training & Coaching',
  'Publishing',
  'Real Estate',
  'Recreational Facilities & Services',
  'Religious Institutions',
  'Research',
  'Restaurants',
  'Retail',
  'Sports',
  'Staffing & Recruiting',
  'Supermarkets',
  'Telecommunications',
  'Textiles',
  'Transportation/Trucking/Railroad',
  'Utilities',
  'Veterinary',
  'Wholesale'
];

export const DEPARTMENTS = [
  'Accounting & Finance',
  'Administration',
  'Analytics & Data Science',
  'Audit & Compliance',
  'Brand Management',
  'Business Development',
  'Communications',
  'Corporate Strategy',
  'Customer Service',
  'Design',
  'Digital Marketing',
  'Engineering',
  'Events & Public Relations',
  'Facilities Management',
  'Health & Safety',
  'Human Resources',
  'Information Technology',
  'Innovation & Research',
  'International Operations',
  'Legal',
  'Logistics & Supply Chain',
  'Marketing',
  'Operations',
  'Product Development',
  'Production & Manufacturing',
  'Project Management',
  'Quality Assurance',
  'Research & Development',
  'Risk Management',
  'Sales & Business Development',
  'Security',
  'Supply Chain Management',
  'Technical Support',
  'Training & Development',
  'Treasury & Investment'
];

export const COMPANY_SIZES = [
  'Small (1-50)',
  'Medium (51-500)',
  'Large (501-5000)',
  'Enterprise (5000+)'
];